services:
  - name: marketplace-indexer
    type: web
    env: docker
    rootDir: marketplaceIndexer
    dockerComposeFile: marketplaceIndexer/docker-compose.yml
    envVars:
      - key: DATABASE_URL
        value: <replace-with-your-actual-db-url>
    autoDeploy: true