services:
  - name: marketplace-indexer
    type: web
    env: docker
    rootDir: marketplaceIndexer
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        value: <render-postgres-url>
      - key: RPC_HTTP_URL
        value: <your-rpc-url>
      - key: PORT
        value: 8080